"""Initial migration for PostgreSQL

Revision ID: 04866fb4e82d
Revises: 
Create Date: 2024-08-24 14:15:31.410977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04866fb4e82d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terminal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ekstra', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=15), nullable=True),
    sa.Column('ucret', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=True),
    sa.Column('bakiye', sa.Float(), nullable=True),
    sa.Column('bakiye_ortak', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('otobus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plaka', sa.String(length=15), nullable=False),
    sa.Column('bakiye', sa.Float(), nullable=True),
    sa.Column('tag_id', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['firma.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gecis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gecis_zamani', sa.DateTime(), nullable=True),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=False),
    sa.Column('odeme', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['otobus.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gecis')
    op.drop_table('otobus')
    op.drop_table('user')
    op.drop_table('terminal')
    op.drop_table('firma')
    # ### end Alembic commands ###
